"""Summarize command for knowledge graph.

Generates LLM-powered summaries of the entire knowledge graph or focused on a specific topic.
"""
import typer
from typing import Annotated, Optional
from pathlib import Path
from rich.panel import Panel
from rich.markdown import Markdown

from src.models import GraphScope
from src.cli.output import console, print_error, print_json, print_warning
from src.cli.utils import resolve_scope, EXIT_ERROR
from src.llm import LLMUnavailableError
from src.graph import get_service, run_graph_operation


def _load_entities(scope: GraphScope, topic: Optional[str] = None, project_root: Optional[Path] = None) -> list[dict]:
    """Load relevant entities from the knowledge graph.

    Args:
        scope: Graph scope to query
        topic: Optional topic to filter entities
        project_root: Project root path (required for PROJECT scope)

    Returns:
        List of entity dictionaries
    """
    # Load all entities from the graph
    entities = run_graph_operation(get_service().list_entities(scope=scope, project_root=project_root, limit=None))

    # Filter by topic if provided
    if topic:
        entities = [
            e for e in entities
            if topic.lower() in e.get("name", "").lower() or topic.lower() in e.get("summary", "").lower()
        ]

    return entities


def _generate_summary(scope: GraphScope, topic: Optional[str] = None, project_root: Optional[Path] = None) -> str:
    """Generate LLM summary from graph.

    Args:
        scope: Graph scope to query
        topic: Optional topic focus
        project_root: Project root path (required for PROJECT scope)

    Returns:
        Summary text generated by LLM
    """
    # Call GraphService.summarize() which handles both entity loading and LLM generation
    summary_text, entity_count = run_graph_operation(
        get_service().summarize(scope=scope, project_root=project_root, topic=topic)
    )

    return summary_text


def summarize_command(
    topic: Annotated[
        Optional[str],
        typer.Argument(help="Topic to summarize (omit for whole graph)")
    ] = None,
    global_scope: Annotated[
        bool,
        typer.Option("--global", "-g", help="Use global scope")
    ] = False,
    project_scope: Annotated[
        bool,
        typer.Option("--project", "-p", help="Use project scope")
    ] = False,
    format: Annotated[
        Optional[str],
        typer.Option("--format", "-f", help="Output format: json")
    ] = None,
    quiet: Annotated[
        bool,
        typer.Option("--quiet", "-q", help="Suppress non-essential output")
    ] = False,
):
    """Generate a summary of the knowledge graph.

    Without a topic argument, summarizes the entire knowledge graph.
    With a topic, generates a focused summary about that specific topic.

    Examples:
        graphiti summarize
        graphiti summarize "architecture decisions"
        graphiti summarize "llm integration" --format json
    """
    try:
        # Resolve scope
        scope, project_root = resolve_scope(global_scope, project_scope)

        # Determine mode and set up spinner
        if topic is None:
            # Whole-graph summary
            status_msg = "Summarizing knowledge graph..."
        else:
            # Topic-focused summary
            status_msg = f"Summarizing knowledge about '{topic}'..."

        # Show spinner while loading and generating
        with console.status(status_msg) as status:
            # Load entities for count display
            entities = _load_entities(scope, topic, project_root)

            # Update spinner with count
            if topic is None and len(entities) > 0:
                status.update(f"Summarizing {len(entities)} entities...")

            # Check if any entities found
            if not entities:
                if topic is None:
                    print_warning("No knowledge found to summarize.")
                else:
                    print_warning(f"No knowledge found about '{topic}'.")
                raise typer.Exit(0)

            # Generate summary via LLM
            summary_text = _generate_summary(scope, topic, project_root)

        # Output results
        if format == "json":
            print_json({
                "summary": summary_text,
                "scope": scope.value,
                "topic": topic,
                "entity_count": len(entities),
            })
        else:
            # Rich panel display
            title = f"Knowledge Summary{' - ' + topic if topic else ''}"
            panel = Panel(
                Markdown(summary_text),
                title=title,
                border_style="cyan",
                padding=(1, 2),
            )
            console.print(panel)

            if not quiet:
                console.print(f"\n[dim]Summarized {len(entities)} entities from {scope.value} graph[/dim]")

    except LLMUnavailableError:
        print_error(
            "LLM unavailable. Cannot generate summary.",
            suggestion="Run 'graphiti health' for diagnostics."
        )
        raise typer.Exit(EXIT_ERROR)
    except Exception as e:
        print_error(f"Failed to generate summary: {str(e)}")
        raise typer.Exit(EXIT_ERROR)
